stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/pima_diabetes.csv
    outs:
      - data/preprocessed/pima_diabetes_clean.csv
    metrics:
      - metrics/preprocess_metrics.json:
          cache: false
  
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/preprocessed/pima_diabetes_clean.csv
    outs:
      - models/random_forest_model.pkl
    metrics:
      - metrics/train_metrics.json:
          cache: false
  
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/random_forest_model.pkl
    metrics:
      - metrics/evaluate_metrics.json:
          cache: false
    plots:
      - confusion_matrix.png
      - feature_importance.png 